---

build:
    - MANIFEST.in
    - Dockerfile
    - .dockerignore
    - scripts/**
docs:
    - docs/**
    - README.rst
    - AUTHORS.rst
    - CONTRIBUTING.rst
    - CHANGELOG.rst
src:
    - src/**
    - pyproject.toml
tests:
    - tests/**
