name: 'Python Semantic Release'

description: 'Automatic Semantic Versioning for Python projects'

inputs:
  additional_options:
    description: 'Additional options for the publish command. Example: --noop'
    required: false
  directory:
    description: 'Sub-directory to cd into before running semantic-release'
    default: '.'
    required: false
  github_token:
    description: 'GitHub token used to push release notes and new commits/tags'
    required: true
  pypi_token:
    description: 'PyPI API token'
    required: false
  repository_username:
    description: 'Username with project access to push to Artifact Repository'
    required: false
  repository_password:
    description: 'Password or token to the account specified in repository_username'
    required: false
  git_committer_name:
    description: 'The human name for the “committer” field'
    required: false
  git_committer_email:
    description: 'The email address for the “committer” field'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
