---
name: Python Semantic Release

description: Automatic Semantic Versioning for Python projects

inputs:
  root_options:
    default: "-v"
    required: false
    description: |
      Additional options for the main command. Example: -vv --noop

  directory:
    default: "."
    required: false
    description: Sub-directory to cd into before running semantic-release

  github_token:
    type: string
    required: true
    description: GitHub token used to push release notes and new commits/tags

  git_committer_name:
    type: string
    required: false
    description: The human name for the “committer” field

  git_committer_email:
    type: string
    required: false
    description: The email address for the “committer” field

  ssh_public_signing_key:
    type: string
    required: false
    description: The ssh public key used to sign commits

  ssh_private_signing_key:
    type: string
    required: false
    description: The ssh private key used to sign commits

  # `semantic-release version` command line options
  prerelease:
    type: string
    required: false
    description: |
      Force the next version to be a prerelease. Set to "true" or "false".

  prerelease_token:
    type: string
    required: false
    description: "Force the next version to use this prerelease token, if it is a prerelease"

  force:
    type: string
    required: false
    description: |
      Force the next version to be a major release. Must be set to
      one of "prerelease", "patch", "minor", or "major".

  commit:
    type: string
    required: false
    description: Whether or not to commit changes locally. Defaults are handled
      by python-semantic-release internal version command.

  tag:
    type: string
    required: false
    description: |
      Whether or not to make a local version tag. Defaults are handled
      by python-semantic-release internal version command.

  push:
    type: string
    required: false
    description: |
      Whether or not to push local commits to the Git repository. See
      the configuration page for defaults of `semantic-release version`
      for how the default is determined between push, tag, & commit.

  changelog:
    type: string
    required: false
    description: |
      Whether or not to update the changelog.

  vcs_release:
    type: string
    required: false
    description: |
      Whether or not to create a release in the remote VCS, if supported

  build_metadata:
    type: string
    required: false
    description: |
      Build metadata to append to the new version

outputs:
  released:
    description: |
      "true" if a release was made, "false" otherwise

  version:
    description: |
      The newly released version if one was made, otherwise the current version

  tag:
    description: |
      The Git tag corresponding to the version output

runs:
  using: docker
  image: Dockerfile
