A_FULL_VERSION_STRING = "1.11.567"
A_PRERELEASE_VERSION_STRING = "2.3.4-dev.23"
A_FULL_VERSION_STRING_WITH_BUILD_METADATA = "4.2.3+build.12345"

EXAMPLE_REPO_OWNER = "example_owner"
EXAMPLE_REPO_NAME = "example_repo"

COMMIT_MESSAGE = "{version}\n\nAutomatically generated by python-semantic-release"

# Different in-scope commits that produce a certain release type
ANGULAR_COMMITS_PATCH = [
    "fix: something annoying\n",
    "fixup the bugfix\n",
    "oops it broke again\n",
    "fix\n",
    "fix\n",
    "fix\n",
    "fix\n",
    "fix: release the bugfix-fix"
]
ANGULAR_COMMITS_MINOR = [
    "feat: something special\n",
    "fix: needed a tweak\n",
    "tweaked again\n",
    "tweaked again\n",
    "tweaked again\n",
    "fix\n",
    "fix\n",
    "feat: last minute rush order\n",
]
# Take previous commits and insert a breaking change
ANGULAR_COMMITS_MAJOR = ANGULAR_COMMITS_MINOR.copy()
ANGULAR_COMMITS_MINOR.insert(
    4,
    "fix!: big change\n\nBREAKING CHANGE: reworked something for previous feature\n"
)
